# Generated by Django 4.2 on 2023-04-17 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('C', 'Client'),
                                                        ('P', 'Professional')], default='C', max_length=1)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                 to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('professional_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profession', models.CharField(choices=[('PLU', 'Plumber'),
                                                         ('GAR', 'Gardener'),
                                                         ('ELE', 'Electrician'),
                                                         ('TIN', 'Tinsmith'),
                                                         ('PAI', 'Painter'),
                                                         ('LOC', 'Locksmith'),
                                                         ('EXT', 'Exterminator'),
                                                         ('GAT', 'GasTechnician'),
                                                         ('ACT', 'AirConditioningTechnician'),
                                                         ('RET', 'RefrigeratorTechnician'),
                                                         ('CLE', 'Cleaner'),
                                                         ('HAN', 'Handyman')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
            options={
                'db_table': 'professional',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
