# Generated by Django 4.2.1 on 2023-05-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_test_data'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
    ]
