# Generated by Django 4.1.7 on 2023-04-12 11:44

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('ClientID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Birthday', models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Birthday')),
            ],
            options={
                'db_table': 'client',
            },
            bases=('user.profile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
