# Generated by Django 4.1.7 on 2023-04-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('images_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('likes', models.PositiveIntegerField()),
            ],
        ),
    ]
