# Generated by Django 4.2 on 2023-04-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proImages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterModelTable(
            name='images',
            table='Images',
        ),
    ]
