# Generated by Django 4.1.7 on 2023-04-12 11:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('ProfessionalID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Profession', models.CharField(blank=True, choices=[('PLU', 'Plumber'), ('GAR', 'Gardener'), ('ELE', 'Electrician'), ('TIN', 'Tinsmith'), ('PAI', 'Painter'), ('LOC', 'Locksmith'), ('EXT', 'Exterminator'), ('GAT', 'GasTechnician'), ('ACT', 'AirConditioningTechnician'), ('RET', 'RefrigeratorTechnician'), ('CLE', 'Cleaner'), ('HAN', 'Handyman')], max_length=3)),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'professional',
            },
            bases=('user.profile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
