# Generated by Django 4.1.7 on 2023-04-13 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('rating',
                 models.CharField(choices=[('1', 'One Star'), ('2', 'Two Stars'), ('3', 'Three Stars'),
                                           ('4', 'Four Stars'), ('5', 'Five Stars'), ('UN', 'Unspecified')],
                                  default='UN', max_length=2)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_id', models.CharField(max_length=512)),
                ('professional_id', models.CharField(max_length=512)),
            ],
        ),
    ]
