# Generated by Django 4.1.7 on 2023-04-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('professional_id', models.PositiveIntegerField()),
                ('start_day', models.DateTimeField()),
                ('end_day', models.DateTimeField()),
                ('meeting_time', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='TypeOfJob',
            fields=[
                ('typeOfJob_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('professional_id', models.PositiveIntegerField()),
                ('typeOfJob_name', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'TypeOfJob',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('professional_id', models.PositiveIntegerField()),
                ('client_id', models.PositiveIntegerField()),
                ('start_appointment', models.DateTimeField()),
                ('end_appointment', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
                ('typeOfJob_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='reservation.typeofjob')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
    ]
