# Generated by Django 4.1.7 on 2023-04-11 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_day', models.DateTimeField()),
                ('end_day', models.DateTimeField()),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='TypeOfJob',
            fields=[
                ('typeOfJob_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('typeOfName', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'TypeOfJob',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_appointment', models.DateTimeField()),
                ('end_appointment', models.DateTimeField()),
                ('summary', models.TextField()),
                ('typeOfJob_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.typeofjob')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
    ]
