# Generated by Django 4.1.7 on 2023-04-17 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatmessage',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('professional_id', models.CharField(max_length=512)),
                ('client_id', models.CharField(max_length=512)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'Chatmessage',
            },
        ),
    ]
