# Generated by Django 4.2 on 2023-04-23 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_test_data'),
        ('chatmessage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('C', 'Client'), ('P', 'Professional')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='professional_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.professional'),
        ),
    ]
